# Generated by Django 4.0.3 on 2022-04-03 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('primerParcial', models.CharField(default='Nota no disponible', max_length=22)),
                ('segundoParcial', models.CharField(default='Nota no disponible', max_length=22)),
                ('TercerParcial', models.CharField(default='Nota no disponible', max_length=22)),
                ('faltas', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.CharField(default='Tarea de clases', max_length=255)),
                ('nota', models.IntegerField(default=-1, null=True)),
                ('entregado', models.BooleanField(default=False)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.estudiante')),
            ],
        ),
    ]
